fetch("https://www.apicountries.com/countries")
.then(res=>{
    return res.json()
}
)
// .then(
//     data => {
//         console.log(data[0])
//         console.log("The name of the country is "+data[0].name)
//         console.log("It's top level domain is "+data[0].topLevelDomain)
//         console.log("It's alpha two code is "+data[0].alpha2Code)
//         console.log("It's alpha three code is "+data[0].alpha3Code)
//         console.log("It's country calling code is "+data[0].callingCodes)
//         console.log("It's capital city is "+data[0].capital)
//         console.log("it's alt spellings is "+data[0].altSpellings)
//         console.log("It's is located in "+data[0].subregion)
//         console.log("It's continant is "+data[0].region)
//         console.log("It;s population is "+data[0].population)
//         console.log("It's latitude is "+data[0].latlng[0]+"It's latitude is"+data[0].latlng[1])
//         console.log("It's nick name is "+data[0].demonym)
//         console.log("It's are is "+data[0].area)
//         console.log("It's time zone is "+data[0].timezones)
//         console.log("It's sharing his border with "+data[0].borders)
//         console.log("It's native name is "+data[0].nativeName)
//         console.log("It's numeric code is "+data[0].numericCode)
//         console.log("It's curriencies is "+data[0].currencies[0].code+" It's currency is "+data[0].currencies[0].name+ " It's currency symbol is "+data[0].currencies[0].symbol)
//         console.log("It's br is "+data[0].translations.br+" It's pt is "+data[0].translations.pt+" It's nl is "+data[0].translations.nl+" It's hr is "+data[0].translations.hr+" It's fa is "+data[0].translations.fa+" It's de is "+data[0].translations.de+" It's es is "+data[0].translations.es+" It's fr is "+data[0].translations.fr+" It's ja is "+data[0].translations.ja+" It's it is "+data[0].translations.it+"  It's hu is "+data[0].translations.hu)
//         console.log("It's also a part of "+data[0].regionalBlocs[0].acronym+" The name of orginazation is "+data[0].regionalBlocs[0].name)
//         console.log("It's cioc is "+data[0].cioc+" It is "+data[0].independent?" a independent country!":" not a independent country!")
//     }
// )
.then(dataa=>{
    console.log(dataa[156])
    console.log("The name of the country is "+dataa[156].name)
    console.log("It's top level domin is "+dataa[156].topLevelDomain)
        console.log("It's alpha2Code is "+dataa[156].alpha2Code)
        console.log("It's alpha3Code is "+dataa[156].alpha3Code)
        console.log("It's callingCodes is "+dataa[156].callingCodes)
        console.log("It's capital is "+dataa[156].capital)
        console.log("It's altSpellings is "+dataa[156].altSpellings)
        console.log("It's subregion is "+dataa[156].subregion)
        console.log("It's region is "+dataa[156].region)
        console.log("It's population is "+dataa[156].population)
        console.log("It's latitude is "+dataa[156].latlng[0]+" and It's longitude "+dataa[156].latlng[1])
        console.log("It's demonym is "+dataa[156].demonym)
        console.log("It's area is "+dataa[156].area)
        console.log("It's gini is "+dataa[156].gini)
        console.log("It's timezones is "+dataa[156].timezones)
        console.log("It's borders is "+dataa[156].borders)
        console.log("It's nativeName is "+dataa[156].nativeName)
        console.log("It's currencies code is "+dataa[156].currencies[0].code+" It's currencies name is "+dataa[156].currencies[0].name+" It's currencies symbol is "+dataa[156].currencies[0].symbol)
        console.log("It's languages iso639_1 is "+dataa[156].languages[0].iso639_1+" It's languages iso639_2 is "+dataa[156].languages[0].iso639_2+" It's languages name is "+dataa[156].languages[0].name+"It's languages nativeName is"+dataa[156].languages[0].nativeName)
        console.log("It's translations is "+dataa[156].translations.br+" It's translations is "+dataa[156].translations.pt+" It's translations is "+dataa[156].translations.nl+"It's translations is"+dataa[156].translations.hr+"It's translations is "+dataa[156].translations.fa+"It's translations is "+dataa[156].translations.de+"It's translations is "+dataa[156].translations.es+"It's translations is "+dataa[156].translations.fr+"It's translations is "+dataa[156].translations.ja+"It's translations is "+dataa[156].translations.it+"It's translations is "+dataa[156].translations.hu)
        console.log("It's regionalBlocs is "+dataa[156].regionalBlocs[0].acronym+" It's regionalBlocs is "+dataa[156].regionalBlocs[0].name)


})