let element=document.getElementById('first')
console.log(element)
console.log(element.textContent)
let element1=document.getElementsByClassName('first')
console.log(element1[0])
console.log(element1[1].textContent)
let element2=document.getElementsByTagName('p')
console.log(element2)
console.log(element2[3].textContent)
let element3=document.querySelector('.query')
console.log(element3)
console.log(element3.textContent)